// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQeFmMQuqNje5I6rq58xG2XEpGcSQQ4w',
    appId: '1:20244533550:web:2dfce42d95455bfceb2abf',
    messagingSenderId: '20244533550',
    projectId: 'flurd-effa0',
    authDomain: 'flurd-effa0.firebaseapp.com',
    storageBucket: 'flurd-effa0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgJP26ZehNoUsOtmQGPtQj0LH1k7xuDJM',
    appId: '1:20244533550:android:b0286f594b382d14eb2abf',
    messagingSenderId: '20244533550',
    projectId: 'flurd-effa0',
    storageBucket: 'flurd-effa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ZVxiaegpcd0Yhj3uysMM0fA8qAbRo9o',
    appId: '1:20244533550:ios:6b584a10bc820583eb2abf',
    messagingSenderId: '20244533550',
    projectId: 'flurd-effa0',
    storageBucket: 'flurd-effa0.firebasestorage.app',
    iosBundleId: 'com.example.flurd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ZVxiaegpcd0Yhj3uysMM0fA8qAbRo9o',
    appId: '1:20244533550:ios:6b584a10bc820583eb2abf',
    messagingSenderId: '20244533550',
    projectId: 'flurd-effa0',
    storageBucket: 'flurd-effa0.firebasestorage.app',
    iosBundleId: 'com.example.flurd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYQeFmMQuqNje5I6rq58xG2XEpGcSQQ4w',
    appId: '1:20244533550:web:95c622629a4908a7eb2abf',
    messagingSenderId: '20244533550',
    projectId: 'flurd-effa0',
    authDomain: 'flurd-effa0.firebaseapp.com',
    storageBucket: 'flurd-effa0.firebasestorage.app',
  );

}